### ISSUE TITLE
Passing spotify url is crashing the bot

### ISSUE THREAD

**Issue by Chinmay-KB** [Chinmay-KB/bajaobot#2]
```
Error: Streaming from Spotify is not supported. Please use search() to find a similar track on YouTube or SoundCloud instead.
    at Object.stream (/Users/user/bajao/node_modules/play-dl/dist/index.js:14:2744)
    at Queue.<anonymous> (/Users/user/bajao/dist/commands/play.js:67:50)
    at Generator.next (<anonymous>)
    at /Users/user/bajao/dist/commands/play.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/user/bajao/dist/commands/play.js:23:12)
    at Queue.onBeforeCreateStream (/Users/user/bajao/dist/commands/play.js:66:32)
    at Queue.<anonymous> (/Users/user/bajao/node_modules/discord-player/dist/Structures/Queue.js:655:48)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/user/bajao/node_modules/tslib/tslib.js:114:62)
```

**Comment by Chinmay-KB** [comment]
After checking with the developer of discord-player, this is not supported because of DRM issues.
